version: "3.7"
services:
  movieLibrary:
    image: node:16
    working_dir: /app
    volumes:
      - ../:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CODESANDBOX_SSE=true
    command: bash -c "npm install && npm run start"
    ports:
      - "8085:8000"
